version: "3"
services:
    db:
        image: mysql:latest
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: websitert7
            MYSQL_USER: fredo
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - mynetwork

    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: websitert7:1.0
        container_name: web-container
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - mynetwork
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: websitert7
            DB_USERNAME: root
            DB_PASSWORD: password

networks:
    mynetwork:
        driver: bridge
